version: "3"
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "5050:5050"
    environment:
      - ATLAS_URI=${ATLAS_URI}
      - PORT=${PORT}
      - SECRET=${SECRET}
